### ISSUE TITLE
[DEPR]: Enzyme

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/public-engineering#195]
### Proposal Date

2023-05-31

### Target Ticket Acceptance Date

2023-06-16

### Earliest Open edX Named Release Without This Functionality

Quince - 2023-10

### Rationale

Enzyme was largely the tool of choice for most JS tests throughout the Open edX platform until React `testing-library` came out, which afforded developers a simpler way to write tests that more closely resembled how the web pages are used in practice by largely not relying on internal implementation details of the component. See https://testing-library.com/docs/guiding-principles/ for more details about `testing-library`'s philosophy.

However, while most new tests being written throughout Open edX are using React `testing-library`, there stills exists a large number of Enzyme tests. Having these tests around would usually not be an issue, but it has recently come to our attention that Enzyme is no longer maintained; its maintainers and the community have publicly mentioned there are no plans to create a React 18 adapter for Enzyme. See more details here: https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl

While it does not have any immediate impact on Open edX given it is largely running either React 16 and/or 17, Enzyme's lack of support for React 18  will impact and block an imminent upgrade to React 18 in the future.

### Removal

Any repository which intends to upgrade to React 18 will need to remove its usage of Enzyme throughout its test suites. These Enzyme tests may be refactored using the suggestions made below.

### Replacement

We recommend the use of React [`testing library`](https://testing-library.com/docs/react-testing-library/intro/) and/or [`react-test-renderer`](https://legacy.reactjs.org/docs/test-renderer.html).

Existing tests that rely on Enzyme will need to be refactored to use an alternative like React `testing-library` prior to any attempts to upgrade to React 18.

### Deprecation

Stub: we may be able to include build-time deprecation warnings within `@edxfrontend-build` to detect when a consuming MFE is using Enzyme based on whether it's installed in the MFE's `package.json` file.

### Migration

Incremental migration is acceptable. Open edX is currently running React 16 in most places, but React 17 in a handful of others. Once React 18 becomes more imminent, refactoring away from Enzyme will become more important to not become a blocker for a future React 18 upgrade.

### Additional Info

* https://discuss.openedx.org/t/deprecation-removal-enzyme-public-engineering-195/10259

```[tasklist]
#### Outstanding Issues
- [ ] https://github.com/openedx/frontend-component-cookie-policy-banner/issues/440
- [ ] https://github.com/openedx/edx-platform/issues/35245
- [ ] https://github.com/openedx/edx-platform/pull/36372
```

```[tasklist]
#### Issues
- [ ] https://github.com/openedx/wg-frontend/issues/166
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/263
- [ ] https://github.com/openedx/frontend-app-library-authoring/issues/166
- [ ] https://github.com/openedx/paragon/issues/2325
```

```[tasklist]
#### PRs
- [ ] https://github.com/openedx/open-edx-proposals/pull/487
- [ ] https://github.com/openedx/open-edx-proposals/pull/501
- [ ] https://github.com/openedx/frontend-app-authn/pull/1128
- [ ] https://github.com/openedx/frontend-app-authn/pull/1117
- [ ] https://github.com/openedx/frontend-app-authn/pull/1115
- [ ] https://github.com/openedx/frontend-app-authn/pull/1122
- [ ] https://github.com/openedx/frontend-app-authn/pull/1116
- [ ] https://github.com/openedx/frontend-app-authn/pull/1123
- [ ] https://github.com/openedx/frontend-app-learner-portal-programs/pull/297
- [ ] https://github.com/openedx/frontend-app-program-console/pull/160
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/276
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/295
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/378
- [ ] https://github.com/openedx/frontend-app-library-authoring/pull/397
- [ ] https://github.com/openedx/frontend-app-profile/pull/941
- [ ] https://github.com/openedx/frontend-app-payment/pull/844
- [ ] https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/915
- [ ] https://github.com/openedx/frontend-app-admin-portal/pull/1164
- [ ] https://github.com/openedx/frontend-app-ecommerce/pull/359
- [ ] https://github.com/openedx/openedx-tech-radar/pull/19
- [ ] https://github.com/openedx/frontend-lib-content-components/pull/450
- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/770
- [ ] https://github.com/openedx/frontend-platform/pull/615
- [ ] https://github.com/openedx/frontend-component-header/pull/439
- [ ] https://github.com/openedx/frontend-app-account/pull/945
- [ ] https://github.com/openedx/frontend-component-footer/pull/372
- [ ] https://github.com/openedx/paragon/pull/2611
- [ ] https://github.com/openedx/paragon/pull/2581
- [ ] https://github.com/openedx/frontend-component-ai-translations/issues/18
- [ ] frontend-app-publisher
- [ ] frontend-app-support-tools
- [ ] frontend-app-admin-portal
```

**Comment by jesperhodge** [comment]
@adamstankiewicz before we merge this, I would love to add more guidance here on how to migrate away from enzyme. I would like to amend the "Replacement" section with something like this:

"Replacing an enzyme test with react-testing-library means rewriting a lot of code. Thus, for existing tests that you don't want to completely rewrite, we recommend using @muselesscreator 's https://github.com/muselesscreator/react-unit-test-utils as a wrapper for react-test-renderer that can for the most part act as a drop-in-replacement for enzyme without too much work.

For new tests, we recommend at least partially using react-testing-library. It is more powerful in that it allows you also to test multiple components together, test behavior as it appears to users in the browser, and test stateful components, which is not supported by react-test-renderer."

**Comment by arbrandes** [comment]
@Syed-Ali-Abbas-Zaidi, I notice you've been doing this migration accross a few MFEs.  Do you see any PRs missing from the list in the description?  Are you aware of any MFEs or libraries where the migration hasn't been done, yet?

**Comment by dianakhuang** [comment]
@arbrandes What is the current status of this? Should we move it into 'removing'?

**Comment by dianakhuang** [comment]
Since it seems like this is not active and the owners are not being responsive, we're going to move this back into 'Proposed'

**Comment by MaxFrank13** [comment]
Thanks for bringing this back to life. Not being on React 18 is forcing us to stay on version 12 of React Testing Library. We even had a couple PRs with dependency conflicts get merged by renovate:

- [Update PR](https://github.com/openedx/frontend-app-learner-record/pull/280) in Learner Record ([revert PR](https://github.com/openedx/frontend-app-learner-record/commit/ecde2d424df58a15fa4ad198ec293c0ede1f0c1b))
- [Update PR](https://github.com/openedx/frontend-app-profile/pull/768) in Profile ([revert PR](https://github.com/openedx/frontend-app-profile/commit/c922a1cd29c611a991fb0f5c1465ae22cf0d0666))

**Comment by feanil** [comment]
@MaxFrank13 can you provide some more info, it sounds like your repos are already on React Testing Library and so your issues are unrelated to enzyme?  Maybe I missed something?

**Comment by MaxFrank13** [comment]
Yes you're right. It's not directly related. It's just that deprecating Enzyme helps clear the way for React 18, and until then, we have to stay on React Testing Library v12 (the latest is v16). Other than Renovate merging those PRs with conflicts, this isn't really causing problems other than preventing us from staying up to date. 

The only issue I've been able to find that is referencing React 18 upgrades is one for the [React 17 upgrade in platform-roadmap](https://github.com/openedx/platform-roadmap/issues/277), and this Enzyme deprecation issue. Perhaps I'm not looking in the right places or maybe the work just hasn't been prioritized yet.

Worth noting that Enzyme isn't the only blocker for React 18. We'd still need to upgrade other FE dependencies/peerDependencies in places like `frontend-platform` and `frontend-build` to support React 18. And perhaps that's why work on this issue was paused?

**Comment by feanil** [comment]
It sounds like what you actually care about is tracking https://github.com/openedx/platform-roadmap/issues/277 which you're right is not currently being lead/in-progress anymore.

My recommendation is that if there are specifics preventing upgrades in repos you care about to create issues in those repos about the specific upgrades that need to happen and to work with the maintainers to plan/take-on that work.  If you need help with that please let me know but it sounds like your issue is more that "We're not on react 18 yet in learner record and profile" but the root cause of that is not the fact that those repos are still running "Enzyme" but some other blocker or just scheduling the work to do the upgrade.

**Comment by MaxFrank13** [comment]
Ahh thanks for the suggestion. I think I incorrectly assumed that upgrades to `frontend-platform` and `frontend-build` were also waiting on the deprecation of Enzyme. I see now that technically that shouldn't be the case.

**Comment by feanil** [comment]
With https://github.com/openedx/edx-platform/pull/36372 merged, this upgrade is now complete.
