### ISSUE TITLE
[Django 4.2 Support] Add Django 4.2 support in edx/openedx django packages

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/public-engineering#199]
## Description
`edx-arbi-bom` team has started effort on [Django 4.2 upgrade](https://github.com/openedx/platform-roadmap/issues/269).
The next step is to upgrade all the edx and openedx django packages with Django 4.2 support.

```[tasklist]
### Tasks
- [ ] https://github.com/edx/upgrades/issues/133
- [ ] https://github.com/edx/upgrades/issues/124
- [ ] https://github.com/edx/upgrades/issues/131
- [ ] https://github.com/edx/upgrades/issues/145
- [ ] https://github.com/edx/upgrades/issues/146
- [ ] https://github.com/edx/upgrades/issues/135
- [ ] https://github.com/edx/upgrades/issues/138
- [ ] https://github.com/edx/upgrades/issues/147
- [ ] https://github.com/edx/upgrades/issues/140
- [ ] https://github.com/edx/upgrades/issues/149
- [ ] https://github.com/edx/upgrades/issues/388
- [ ] https://github.com/edx/upgrades/issues/153
- [ ] https://github.com/edx/upgrades/issues/142
- [ ] https://github.com/edx/upgrades/issues/162
- [ ] https://github.com/edx/upgrades/issues/163
- [ ] https://github.com/edx/upgrades/issues/167
- [ ] https://github.com/edx/upgrades/issues/168
- [ ] https://github.com/edx/upgrades/issues/174
- [ ] https://github.com/edx/upgrades/issues/134
- [ ] https://github.com/edx/upgrades/issues/185
- [ ] https://github.com/edx/upgrades/issues/151
- [ ] https://github.com/edx/upgrades/issues/172
- [ ] https://github.com/edx/upgrades/issues/176
- [ ] https://github.com/edx/upgrades/issues/126
- [ ] https://github.com/edx/upgrades/issues/158
- [ ] https://github.com/edx/upgrades/issues/156
- [ ] https://github.com/edx/upgrades/issues/166
- [ ] https://github.com/edx/upgrades/issues/155
- [ ] https://github.com/edx/upgrades/issues/165
- [ ] https://github.com/edx/upgrades/issues/136
- [ ] https://github.com/edx/upgrades/issues/150
- [ ] https://github.com/edx/upgrades/issues/132
- [ ] https://github.com/edx/upgrades/issues/157
- [ ] https://github.com/edx/upgrades/issues/180
- [ ] https://github.com/edx/upgrades/issues/169
- [ ] https://github.com/edx/upgrades/issues/152
- [ ] https://github.com/edx/upgrades/issues/139
- [ ] https://github.com/edx/upgrades/issues/190
- [ ] https://github.com/edx/upgrades/issues/128
- [ ] https://github.com/edx/upgrades/issues/129
- [ ] https://github.com/edx/upgrades/issues/148
- [ ] https://github.com/edx/upgrades/issues/125
- [ ] https://github.com/edx/upgrades/issues/160
- [ ] https://github.com/edx/upgrades/issues/161
- [ ] https://github.com/edx/upgrades/issues/154
- [ ] https://github.com/edx/upgrades/issues/164
- [ ] https://github.com/edx/upgrades/issues/143
- [ ] https://github.com/edx/upgrades/issues/170
- [ ] https://github.com/edx/upgrades/issues/183
- [ ] https://github.com/edx/upgrades/issues/189
- [ ] https://github.com/edx/upgrades/issues/141
- [ ] https://github.com/edx/upgrades/issues/191
- [ ] https://github.com/edx/upgrades/issues/181
- [ ] https://github.com/edx/upgrades/issues/179
- [ ] https://github.com/edx/upgrades/issues/137
- [ ] https://github.com/edx/upgrades/issues/144
- [ ] https://github.com/edx/upgrades/issues/173
- [ ] https://github.com/edx/upgrades/issues/122
- [ ] https://github.com/edx/upgrades/issues/123
- [ ] https://github.com/edx/upgrades/issues/130
- [ ] https://github.com/edx/upgrades/issues/177
- [ ] https://github.com/edx/upgrades/issues/159
- [ ] https://github.com/edx/upgrades/issues/192
- [ ] https://github.com/edx/upgrades/issues/184
- [ ] https://github.com/edx/upgrades/issues/188
- [ ] https://github.com/edx/upgrades/issues/186
- [ ] https://github.com/edx/upgrades/issues/187
- [ ] https://github.com/edx/upgrades/issues/182
- [ ] https://github.com/edx/upgrades/issues/175
- [ ] https://github.com/edx/upgrades/issues/127
- [ ] https://github.com/edx/upgrades/issues/171
- [ ] https://github.com/edx/upgrades/issues/178
```
