### ISSUE TITLE
[DEPR]: edx-sphinx-theme

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#200]
### Proposal Date

29 November 2022

### Target Ticket Acceptance Date

13 December 2022

### Earliest Open edX Named Release Without This Functionality

Palm - 2023-04

### Rationale

* There is no maintainer for this theme.
* We've decided to start using an off-the-shelf them for Open edX docs(sphinx-book-theme)
* Maintaining our own theme adds more maintenance burden.

### Removal

This repository https://github.com/openedx/edx-sphinx-theme/ will be archived after doing one more PyPI release which will indicate that the project is deprecated and no longer maintained.

### Replacement

Anyone building docs should use the [sphinx-book-theme](https://github.com/openedx/docs.openedx.org/blob/main/requirements/base.in#L5) instead.

### Deprecation

- [x] openedx/edx-sphinx-theme#190
- [x] openedx/docs.openedx.org#230
- [x] openedx/docs.openedx.org#231
- [x] openedx/edx-sphinx-theme#193

### Migration

People can switch to the sphinx-book-theme by adding the `sphinx-book-theme` to their requirements and updating their sphinx conf.py to use the sphinx-book-theme.

### Additional Info

Discourse Post: https://discuss.openedx.org/t/deprecation-removal-edx-sphinx-theme/8817
