### ISSUE TITLE
[DEPR]: Mark Insights repos as deprecated and move to edx-unsupported

### ISSUE THREAD

**Issue by bmtcril** [openedx/public-engineering#227]
### Proposal Date

2024-02-07

### Target Ticket Acceptance Date

2024-02-29

### Earliest Open edX Named Release Without This Functionality

Redwood - 2024-04

### Rationale

Per the accepted #221 DEPR, this issue will cover the first steps of removal. This is just a sub-ticket for more easily managing this extraordinarily large DEPR.

### Removal

1.  Updating the READMEs and documentation associated with Insights and it's repositories to indicate that it is officially deprecated and unsupported.
2. Moving the repositories to the `openedx-unsupported` Github organization. The expectation is that anyone continuing to run Insights will continue to be able to do so with minimal (or no) changes. If their infrastructure supports following Github redirects this may not require any updates, but configuration may need to be updated to point to the new URLs for projects cloning directly from Github.

The impacted repositories are:

- edx-analytics-pipeline
- edx-analytics-dashboard
- edx-analytics-data-api
- edx-analytics-data-api-client
- edx-analytics-configuration
- edx-analytics-exporter

Documentation will be updated wherever it can be found in docs.openedx.org, discussions with 2U will determine the direction of documentation in docs.edx.org and edx.readthedocs.io since so far as we know they intend to keep running it and the user docs will remain relevant for them.

### Replacement

Overall, Insights is being replaced by [Aspects](https://docs.openedx.org/projects/openedx-aspects/en/latest/index.html) which we're expecting to release in Redwood.

### Additional Info

Discourse Announcement: https://discuss.openedx.org/t/deprecation-insights-repositories-and-docs/12268

### Task List

edx-analytics-pipeline
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-pipeline/pull/896)
- [x] Move the repository to the `openedx-unsupported` Github organization.

edx-analytics-dashboard
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-dashboard/pull/1566)
- [x] Move the repository to the `openedx-unsupported` Github organization.

edx-analytics-data-api
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-data-api/pull/717)
- [x] Move the repository to the `openedx-unsupported` Github organization.

edx-analytics-data-api-client
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-data-api-client/pull/170)
- [x] Move the repository to the `openedx-unsupported` Github organization.

edx-analytics-configuration
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-configuration/pull/117)
- [x] Move the repository to the `openedx-unsupported` Github organization.

edx-analytics-exporter
- [x] Update the README to indicate that it is officially deprecated and unsupported. (https://github.com/openedx/edx-analytics-exporter/pull/94)
- [x] Move the repository to the `openedx-unsupported` Github organization.

Documentation

- [x] Update documentation in docs.openedx.org to remove any references to Insights

**Comment by feanil** [comment]
Posted in discourse here: https://discuss.openedx.org/t/deprecation-insights-repositories-and-docs/12268

**Comment by bmtcril** [comment]
@Zacharis278 absolutely, let me know if you all want to meet up for a quick touch base at any point.

**Comment by bmtcril** [comment]
@Zacharis278 @MichaelRoytman this DEPR has been accepted. I'm not sure when I will get to the work, but the first bit will be updating the READMEs in those repos. I will ping you both on those PRs as they get created.

**Comment by bmtcril** [comment]
@Zacharis278 @MichaelRoytman PRs have been opened to update README on all 6 repos as above.

**Comment by bmtcril** [comment]
Hi @MichaelRoytman (and @HassanJaveed84 who was asking about this in the other ticket). There's also an `openedx-unsupported` repository, which isn't going away, and is where we (Axim / Open edx) archive deprecated repos. We wouldn't move these repositories to `edx` as part of this DEPR, you would want to fork them there at your convenience.

**Comment by bmtcril** [comment]
@MichaelRoytman I see the confusion, I'd put `edx-unsupported` in this ticket description. That was a mistake on my part, it's been updated to `openedx-unsupported`.

**Comment by bmtcril** [comment]
@MichaelRoytman @Zacharis278 @HassanJaveed84 I'm scheduling the archival and move of these repositories on April 30. Please let me know if you would like to coordinate around that, or you can fork and cut over at your convenience between now and then.

**Comment by MichaelRoytman** [comment]
@bmtcril Thanks, Brian. We've got someone looking at how to accommodate the move right now. I'll let the team know and report back if we require any coordination.

**Comment by varshamenon4** [comment]
Hi @bmtcril! Based on our research, it looks like everything should just work after the switchover. That being said, we want to complete the following steps after the changeover:
- Smoke test that github redirects work for each repo locally.
- Set new URLs direct clones in repos (not required for this to work, just to prevent any confusion)
- Share within internal eng org instructions to update existing local clones to point to new repo URL

Can these happen right on April 30th? Would you need to or be able to let us know when the move will happen exactly? Thanks for the help!

**Comment by bmtcril** [comment]
Hi @varshamenon4 , thanks for digging in to this. I think my suggestion would be to fork these repos back into the edx org rather than have them point to the openedx-unsupported. That way you can continue to maintain and bug fix as necessary going forward. Since you would be updating the URLs in downstream repos and local clones anyway, this should let you do the updates and test ahead of April 30 and shouldn't change much of your plan aside from doing the forks and changing the URLs you're updating to.

If you don't want to do that this plan looks fine to me and can happen any time after repos are moved on the 30th. I would be happy to sync up with someone there directly as the changes happen, just let me know who to bother. :)

**Comment by varshamenon4** [comment]
Hi @bmtcril! Thanks for clarifying and suggesting forking instead. It looks like all of the openedx-unsupported repos are read-only, so we would need to fork anyway in order to maintain/bug fix as suggested. Is that correct? In that case, your suggestion makes more sense (to fork and test ahead of April 30). I can plan on moving forward on those steps and will reach back out if I run into any issues. Does that work?

**Comment by bmtcril** [comment]
@varshamenon4 sounds great, feel free to grab me on Slack if you need anything!

**Comment by bmtcril** [comment]
@varshamenon4 I was also told yesterday that there is internal 2U documentation around making sure these forks don't break old releases here (I can't see it, but believe it's true 😄): https://2u-internal.atlassian.net/wiki/spaces/AT/pages/958595796/Forking+repos+back+into+edx+GitHub+org

**Comment by bmtcril** [comment]
Hi everyone, just a reminder that tomorrow is the day we plan to archive and move the Insights repositories. Please let me know if you need any coordination around that!

cc: @varshamenon4 @Zacharis278 @MichaelRoytman @HassanJaveed84

**Comment by bmtcril** [comment]
Repositories have been archived and transferred to the openedx-unsupported github org. Docs updates are happening here: https://github.com/openedx/docs.openedx.org/pull/489

**Comment by bmtcril** [comment]
This part of the deprecation is complete, closing this ticket out

**Comment by MichaelRoytman** [comment]
Hi, Brian. We've had a few team members working on various parts of preparing for the deprecation, so I apologize for not following up sooner. We have forked the repositories successfully, so we are all set on that front! Thank you for your help.

We're still working through product to see what we'll do with Insights longer term, but we'll likely be continuing to run it as-is for the time being until we get to a product decision.
