### ISSUE TITLE
Update all Released Django services to use Node 20

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#230]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/edx-platform/issues/31937
- [ ] https://github.com/openedx/edx-platform/pull/34311
- [ ] https://github.com/openedx/edx-enterprise/issues/2213
```

**Comment by feanil** [comment]
This looks like it's done in edx-platform, credentials and course-discovery, other services are on track to be deprecated so I think it's not as critical.
