### ISSUE TITLE
Jest 26 to 29 Upgrade

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#239]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/frontend-app-ecommerce/pull/372
- [ ] https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/423
- [ ] https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1089
- [ ] https://github.com/openedx/frontend-app-payment/pull/835
- [ ] https://github.com/openedx/frontend-component-cookie-policy-banner/pull/434
- [ ] https://github.com/openedx/frontend-app-communications/pull/181
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/374
- [ ] https://github.com/openedx/frontend-app-discussions/pull/626
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/328
- [ ] https://github.com/openedx/frontend-app-learning/pull/1391
- [ ] https://github.com/openedx/frontend-app-program-console/pull/155
- [ ] https://github.com/openedx/frontend-app-support-tools/pull/385
- [ ] https://github.com/openedx/frontend-app-learner-portal-programs/pull/299
- [ ] https://github.com/openedx/frontend-app-publisher/pull/947
- [ ] https://github.com/openedx/frontend-app-library-authoring/pull/438
- [ ] https://github.com/openedx/frontend-template-application/pull/701
- [ ] https://github.com/openedx/frontend-app-authn/pull/1251
- [ ] https://github.com/edx/frontend-component-header-edx/pull/525
- [ ] https://github.com/edx/frontend-lib-learning-assistant/pull/48
- [ ] https://github.com/edx/frontend-app-exams-dashboard/pull/29
- [ ] https://github.com/edx/frontend-component-footer-edx/pull/366
- [ ] https://github.com/edx/frontend-app-skills/pull/164
- [ ] https://github.com/openedx/frontend-app-account/pull/958
- [ ] https://github.com/openedx/frontend-app-admin-portal/pull/1192
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/256
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/246
- [ ] https://github.com/openedx/frontend-app-ora/pull/193
- [ ] https://github.com/openedx/frontend-app-profile/pull/932
- [ ] https://github.com/openedx/frontend-build/pull/415
- [ ] https://github.com/openedx/frontend-component-ai-translations/pull/15
- [ ] https://github.com/openedx/frontend-component-footer/pull/317
- [ ] https://github.com/openedx/frontend-component-header/pull/369
- [ ] https://github.com/openedx/frontend-enterprise/pull/387
- [ ] https://github.com/openedx/frontend-lib-content-components/pull/475
- [ ] https://github.com/openedx/frontend-lib-special-exams/pull/125
- [ ] https://github.com/openedx/frontend-platform/pull/513
- [ ] https://github.com/openedx/frontend-plugin-framework/pull/59
- [ ] https://github.com/openedx/paragon/pull/3032
- [ ] https://github.com/openedx/react-unit-test-utils/pull/22
```

**Comment by feanil** [comment]
@iamsobanjaved This might be an easier way to track this work.

**Comment by feanil** [comment]
Aulseneo will do some testing for this so that reviews are easier for Adolfo and other CCs

**Comment by feanil** [comment]
This is now completed.
