### ISSUE TITLE
Design tokens

### ISSUE THREAD

**Issue by arbrandes** [openedx/public-engineering#246]
### Description

An epic to group all the work being done for the adoption of Design Tokens.

### Related issues and PRs

```[tasklist]
#### Paragon
- [ ] https://github.com/openedx/paragon/issues/1542
- [ ] https://github.com/openedx/paragon/issues/1543
- [ ] https://github.com/openedx/paragon/issues/1544
- [ ] https://github.com/openedx/paragon/issues/1545
- [ ] https://github.com/openedx/paragon/issues/1546
- [ ] https://github.com/openedx/paragon/issues/1548
- [ ] https://github.com/openedx/paragon/issues/1549
- [ ] https://github.com/openedx/paragon/issues/1938
- [ ] https://github.com/openedx/paragon/issues/1947
- [ ] https://github.com/openedx/paragon/issues/1948
- [ ] https://github.com/openedx/paragon/issues/1968
- [ ] https://github.com/openedx/paragon/issues/1969
- [ ] https://github.com/openedx/paragon/issues/1778
- [ ] https://github.com/openedx/paragon/issues/2014
- [ ] https://github.com/openedx/paragon/issues/2015
- [ ] https://github.com/openedx/paragon/issues/2016
- [ ] https://github.com/openedx/paragon/issues/2017
- [ ] https://github.com/openedx/paragon/issues/2018
- [ ] https://github.com/openedx/paragon/issues/2025
- [ ] https://github.com/openedx/paragon/issues/2026
- [ ] https://github.com/openedx/paragon/issues/2086
- [ ] https://github.com/openedx/paragon/issues/2089
- [ ] https://github.com/openedx/paragon/issues/2170
- [ ] https://github.com/openedx/paragon/issues/2269
```

**Comment by arbrandes** [comment]
@brian-smith-tcril, this might be a duplicate.  Is there some other issue that's tracking DTs?

**Comment by brian-smith-tcril** [comment]
Every open issue in this is on the Paragon repo, I've created a new tracking issue over there https://github.com/openedx/paragon/issues/3816 so we can close this
