### ISSUE TITLE
[DEPR]: Shifting edX-app-ios to openedx-unsupported + Updated documentation

### ISSUE THREAD

**Issue by marcotuts** [openedx/public-engineering#260]
(related: [edx-app-android deprecation](https://github.com/openedx/public-engineering/issues/261))
### Proposal Date

2023-10-02

### Target Ticket Acceptance Date

2024-02-01

### Earliest Open edX Named Release Without This Functionality

Redwood - 2024-04

### Rationale

This ticket is a result of OEP-64, where we ratified the adoption of new code bases for both the iOS and Android mobile applications.This DEPR ticket kicks off a conversation with all involved parties to ensure all mobile app repository documentation/readme details make clear the support level for this repository. 

After this change, we hope new open edx community members will be encouraged to contribute to the new mobile repositories. 

### Removal

This codebase is shifting to no longer be the primary Open edX iOS mobile app, starting with the Redwood named release is our target. The organization of this repo will shift from openedx to openedx-unsupported when this ticket is resolved. 

### Replacement

The new iOS repositoriy is located here: https://github.com/openedx/openedx-app-ios

### Deprecation

1 - Updated documentation / readme details to be coordinated with @openedx/edx-mobile-admin regarding this shift
2 - Eventual github org shift (presumably to be handled by Axim github admins) for this repo to the openedx-unsupported github organizaiton. 

### Migration

We will be looking at migration path for interested community members via - https://github.com/openedx/openedx-app-ios/issues/99

### Additional Info

Please feel free to ask questions about this here or in #wg-product-mobile on slack! 
```[tasklist]
### Tasks
- [x] Update edx-app-ios Readme to reference OEP-64 / new openedx-repository
- [ ] https://github.com/openedx/axim-engineering/issues/1114
- [ ] Update build readme details to reflect git commands for new openedx-unsupported organization
- [ ] Update project About section (Currently links to out of date document)
- [x] Update mobile-announcements Slack channel name / topic / description to reflect "edx-" focus
- [ ] Review "Deprecated" section of DEPR docs to update API queries / etc as needed
- [ ] Update docs.edx.org - https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/mobile.html and other mobiel references
```

**Comment by kdmccormick** [comment]
Closing this as the remaining steps are specific to 2U.
