### ISSUE TITLE
[DEPR]: Shifting edX-app-android to openedx-unsupported + Updated documentation

### ISSUE THREAD

**Issue by marcotuts** [openedx/public-engineering#261]
(related: [edx-app-ios deprecation](https://github.com/openedx/public-engineering/issues/260))

### Proposal Date

2023-10-02

### Target Ticket Acceptance Date

2024-04-10

### Earliest Open edX Named Release Without This Functionality

Redwood - 2024-04

### Rationale

This ticket is a result of OEP-64, where we ratified the adoption of new code bases for both the iOS and Android mobile applications. This DEPR ticket kicks off a conversation with all involved parties to ensure all mobile app repository documentation/readme details make clear the support level for this repository.

After this change, we hope new open edx community members will be encouraged to contribute to the new mobile repositories.

### Removal

This codebase is shifting to no longer be the primary Open edX iOS mobile app, starting with the Redwood named release is our target. The organization of this repo will shift from openedx to openedx-unsupported when this ticket is resolved.

### Replacement

The new Android repository is located here: https://github.com/openedx/openedx-app-android

### Deprecation

1 - Updated documentation / readme details to be coordinated with https://github.com/orgs/openedx/teams/edx-mobile-admin regarding this shift
2 - Eventual github org shift (presumably to be handled by Axim github admins) for this repo to the openedx-unsupported github organization.

### Migration

We will be looking at migration path for interested community members via - https://github.com/openedx/openedx-app-ios/issues/99

### Additional Info

Please feel free to ask questions about this here or in #wg-product-mobile on slack!
```[tasklist]
### Tasks
- [x] Update edx-app-android Readme to reference OEP-64 / new openedx-repository
- [ ] https://github.com/openedx/axim-engineering/issues/1115
- [ ] Move edx-app-android to openedx-unsupported organization
- [ ] Update build readme details to reflect git commands for new openedx-unsupported organization
- [ ] Update project About section (Currently links to out of date document)
- [ ] Review "Deprecated" section of DEPR docs to update API queries / etc as needed
```
