### ISSUE TITLE
[DEPR]: testeng-ci

### ISSUE THREAD

**Issue by kdmccormick** [openedx/public-engineering#265]
### Proposal Date

2024-05-14

### Target Ticket Acceptance Date

2024-05-28

### Earliest Open edX Named Release Without This Functionality

Redwood

### Rationale

This is a tiny repo with a couple Python modules for interacting with GitHub. They are used in a handful of GitHub Actions workflows that open PRs. It could easily be merged into repo-tools.

### Removal

This repository will be archived and it will not be part of the Open edX named release, starting with Redwood.

(the repo contains a redwood.master branch, but it will not get redwood.1 tag if this is accepted in time)

### Replacement

This repo used to have a bunch of scripts used by edX's Jenkins server. Those have mostly all been replaced in a community-friendly way with a mix of GitHub Actions workflows, scripts in app repos, and Tutor.

The remaining module that Open edX still uses, `pull_request_creator`, will be moved into repo-tools: https://github.com/openedx/repo-tools/pull/517

### Deprecation

I'll put a notice in the README.

### Migration

Workflows that currently clone and install testeng-ci for the pull_request_creator tool should instead:

```
git clone https://github.com/openedx/repo-tools
pip install -e .[pull_request_creator]
pull_request_creator ...
```

### Additional Info

N/A

```[tasklist]
### Task List
- [x] Transfer this issue to public-engineering.
- [ ] https://github.com/openedx/repo-tools/pull/517
- [ ] https://github.com/openedx/.github/pull/137
- [ ] https://github.com/openedx/testeng-ci/pull/423
- [ ] https://github.com/openedx/axim-engineering/issues/1154
```

**Comment by kdmccormick** [comment]
Replacement and removal is complete.
