### ISSUE TITLE
PyPI Publish Github Action Master Branch Sunset

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#270]
The official PyPI publish github action is sunsetting using the master branch for updates to the action.

https://github.com/marketplace/actions/pypi-publish#-master-branch-sunset-

We need to update all of our PyPI pubilsh jobs to us the new release/v1 branch.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/xblock-skill-tagging/pull/39                                                                                                               
- [ ] https://github.com/openedx/user-util/pull/27                                                                                                                          
- [ ] https://github.com/openedx/django-lang-pref-middleware/pull/252                                                                                                       
- [ ] https://github.com/openedx/pytest-repo-health/pull/293                                                                                                                
- [ ] https://github.com/openedx/staff_graded-xblock/pull/255                                                                                                               
- [ ] https://github.com/openedx/crowdsourcehinter/pull/165                                                                                                                 
- [ ] https://github.com/openedx/xblock-lti-consumer/pull/491                                                                                                               
- [ ] https://github.com/openedx/repo-tools/pull/540                                                                                                                        
- [ ] https://github.com/openedx/edx-search/pull/152                                                                                                                        
- [ ] https://github.com/openedx/ccx-keys/pull/109                                                                                                                          
- [ ] https://github.com/openedx/django-config-models/pull/369                                                                                                              
- [ ] https://github.com/openedx/django-wiki/pull/252                                                                                                                       
- [ ] https://github.com/openedx/api-doc-tools/pull/287                                                                                                                     
- [ ] https://github.com/openedx/acid-block/pull/174                                                                                                                        
- [ ] https://github.com/openedx/django-require/pull/10                                                                                                                     
- [ ] https://github.com/openedx/xblock-sql-grader/pull/170                                                                                                                 
- [ ] https://github.com/openedx/xblock-in-video-quiz/pull/199                                                                                                              
- [ ] https://github.com/openedx/auth-backends/pull/326                                                                                                                     
- [ ] https://github.com/openedx/edx-val/pull/513                                                                                                                           
- [ ] https://github.com/openedx/olxcleaner/pull/23                                                                                                                         
- [ ] https://github.com/openedx/cc2olx/pull/206                                                                                                                            
- [ ] https://github.com/openedx/MongoDBProxy/pull/24                                                                                                                       
- [ ] https://github.com/openedx/RecommenderXBlock/pull/88                                                                                                                  
- [ ] https://github.com/openedx/edx-proctoring/pull/1219                                                                                                                   
- [ ] https://github.com/openedx/event-bus-kafka/pull/258                                                                                                                   
- [ ] https://github.com/openedx/schoolyourself-xblock/pull/126                                                                                                             
- [ ] https://github.com/openedx/edx-organizations/pull/400                                                                                                                 
- [ ] https://github.com/openedx/edx-submissions/pull/255                                                                                                                   
- [ ] https://github.com/openedx/xss-utils/pull/242                                                                                                                         
- [ ] https://github.com/openedx/edx-ora2/pull/2219                                                                                                                         
- [ ] https://github.com/openedx/web-fragments/pull/214                                                                                                                     
- [ ] https://github.com/openedx/edx-django-release-util/pull/72                                                                                                            
- [ ] https://github.com/openedx/django-pyfs/pull/212                                                                                                                       
- [ ] https://github.com/openedx/event-routing-backends/pull/439                                                                                                            
- [ ] https://github.com/openedx/taxonomy-connector/pull/199                                                                                                                
- [ ] https://github.com/openedx/edx-milestones/pull/86                                                                                                                     
- [ ] https://github.com/openedx/FeedbackXBlock/pull/102                                                                                                                    
- [ ] https://github.com/openedx/openedx-events/pull/377                                                                                                                    
- [ ] https://github.com/openedx/edx-bulk-grades/pull/164                                                                                                                   
- [ ] https://github.com/openedx/edx-enterprise-subsidy-client/pull/98                                                                                                      
- [ ] https://github.com/openedx/openedx-atlas/pull/55                                                                                                                      
- [ ] https://github.com/openedx/codejail-includes/pull/14                                                                                                                  
- [ ] https://github.com/openedx/TinCanPython/pull/25              
- [ ] https://github.com/openedx/opaque-keys/pull/326                                            
- [ ] https://github.com/openedx/event-tracking/pull/305                                         
- [ ] https://github.com/openedx/openedx-chem/pull/86                                            
- [ ] https://github.com/openedx/tutor-contrib-coursegraph/pull/40                                             
- [ ] https://github.com/openedx/edx-celeryutils/pull/297                                                                                                                                         
- [ ] https://github.com/openedx/edx-django-sites-extensions/pull/56                                           
- [ ] https://github.com/openedx/xblock-image-modal/pull/182                                                   
- [ ] https://github.com/openedx/xblock-submit-and-compare/pull/176                                            
- [ ] https://github.com/openedx/completion/pull/307                                                           
- [ ] https://github.com/openedx/code-annotations/pull/112                                                     
- [ ] https://github.com/openedx/xblock-qualtrics-survey/pull/153                                              
- [ ] https://github.com/openedx/xblock-free-text-response/pull/181                                            
- [ ] https://github.com/openedx/django-user-tasks/pull/364                                                    
- [ ] https://github.com/openedx/openedx-calc/pull/105                                                         
- [ ] https://github.com/openedx/help-tokens/pull/216                                                          
- [ ] https://github.com/openedx/enmerkar-underscore/pull/171                                                  
- [ ] https://github.com/openedx/edx-django-utils/pull/432                                                                                                 
- [ ] https://github.com/openedx/super-csv/pull/189                                                                                                                                                                           
- [ ] https://github.com/openedx/edx-when/pull/261                                                                                                         
- [ ] https://github.com/openedx/xblock-sdk/pull/384                                                                                                       
- [ ] https://github.com/openedx/tutor-contrib-aspects/pull/900                                                                                            
- [ ] https://github.com/openedx/DoneXBlock/pull/241                                                                                                       
- [ ] https://github.com/openedx/platform-plugin-aspects/pull/70                                                                                           
- [ ] https://github.com/openedx/edx-toggles/pull/371                                                                                                      
- [ ] https://github.com/openedx/XBlock/pull/770                                                                                                           
- [ ] https://github.com/openedx/openedx-filters/pull/201                                                                                                  
- [ ] https://github.com/openedx/codejail/pull/180                                                                                                         
- [ ] https://github.com/openedx/event-bus-redis/pull/111                                                                                                  
```

**Comment by feanil** [comment]
@CodeWithEmad if you can edit this issue and add all the related PRs to the tasklist that would be super helpful!

**Comment by CodeWithEmad** [comment]
Thanks for adding them.

**Comment by feanil** [comment]
The PRs have merged on all repos, this work is done.
