### ISSUE TITLE
Move on from deprecated pkg_resources api

### ISSUE THREAD

**Issue by farhan** [openedx/public-engineering#273]
Shift the code from `pkg_resources` to `importlib.resources` api

Migration guide: https://importlib-resources.readthedocs.io/en/latest/migration.html
Decision making story: https://github.com/openedx/XBlock/issues/676
Reference PR to take learning from: https://github.com/openedx/xblock-sdk/pull/350/files

**Prerequisites:**
- Support of python 3.8 should be dropped. [Relevant epic](https://github.com/openedx/public-engineering/issues/274)

**Acceptance Criteria:**
- Make sure the repository is using xblock version 5.0.0 or above. Upgrade the version if required, preferably via the make upgrade command.
- There should be no usage of `pkg_resources` in the repository
- Test cases should be passed
- XBlock should perform all of its functionality related to change (loading resources)

```[tasklist]
### Tasks
- [x] xblock https://github.com/openedx/XBlock/issues/676
- [x] feedback-xblock https://github.com/openedx/FeedbackXBlock/pull/58
- [x] xblock-sdk - From code
- [x] acid-block https://github.com/openedx/acid-block/issues/179
- [x] DoneXBlock https://github.com/openedx/DoneXBlock/issues/251
- [x] TinCanPython https://github.com/openedx/TinCanPython/issues/27
- [x] edx-platform https://github.com/openedx/edx-platform/issues/35374
- [x] repo-tools https://github.com/openedx/repo-tools/issues/555
- [x] edx-ora2 https://github.com/openedx/edx-ora2/issues/2225
- [x] edx-cookiecutters https://github.com/openedx/edx-cookiecutters/issues/481
- [x] crowdsourcehinter https://github.com/openedx/crowdsourcehinter/issues/174
- [x] code-annotations https://github.com/openedx/code-annotations/issues/114
- [x] xblock-image-explorer https://github.com/openedx/xblock-image-explorer/issues/150
- [x] xblock-skill-tagging https://github.com/openedx/xblock-skill-tagging/issues/41
- [x] xblock-sdk https://github.com/openedx/xblock-sdk/issues/396
- [x] RecommenderXBlock https://github.com/openedx/RecommenderXBlock/issues/96
- [x] AudioXBlock https://github.com/openedx/AudioXBlock/issues/161
- [x] staff_graded-xblock https://github.com/openedx/staff_graded-xblock/issues/263
- [x] xblock-in-video-quiz https://github.com/openedx/xblock-in-video-quiz/issues/208
- [x] openedx-tutor-plugins https://github.com/openedx/openedx-tutor-plugins/issues/26
- [x] platform-plugin-aspects https://github.com/openedx/platform-plugin-aspects/issues/81
- [x] tutor-contrib-coursegraph https://github.com/openedx/tutor-contrib-coursegraph/issues/42
- [x] ConceptXBlock https://github.com/openedx/ConceptXBlock/issues/159
- [x] xblock-sql-grader https://github.com/openedx/xblock-sql-grader/issues/176
- [x] schoolyourself-xblock https://github.com/openedx/schoolyourself-xblock/issues/133
- [x] xblock-free-text-response https://github.com/openedx/xblock-free-text-response/issues/187
- [x] xblock-qualtrics-survey https://github.com/openedx/xblock-qualtrics-survey/issues/160
- [x] xblock-image-modal https://github.com/openedx/xblock-image-modal/issues/188
- [x] xblock-submit-and-compare https://github.com/openedx/xblock-submit-and-compare/issues/183
- [ ] https://github.com/openedx/edx-platform/pull/36213
```
