### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by irtazaakram** [openedx/public-engineering#274]
Python 3.8 is reaching its End of life 2024-10.

```[tasklist]
### Tasks
- [x] XBlock https://github.com/openedx/XBlock/issues/772
- [x] FeedbackXBlock https://github.com/openedx/FeedbackXBlock/issues/108
- [ ] DoneXBlock https://github.com/openedx/DoneXBlock/issues/243
- [ ] edx-notes-api https://github.com/openedx/edx-notes-api/issues/419
- [ ] opaque-keys https://github.com/openedx/opaque-keys/issues/327
- [ ] openedx-learning https://github.com/openedx/openedx-learning/issues/202
- [ ] xblock-in-video-quiz https://github.com/openedx/xblock-in-video-quiz/issues/200
- [ ] xblock-sdk https://github.com/openedx/xblock-sdk/issues/386
```

**Comment by farhan** [comment]
@sarina Thanks for flagging it, after discussion with Feanil it's in `public-engineering` now

**Comment by ttqureshi** [comment]
assign me @farhan

**Comment by farhan** [comment]
`edx-platform` PR is in [progress](https://github.com/openedx/edx-platform/pull/37160). Once it's merged team will start working on `openedx-translations` repository.
