### ISSUE TITLE
Upgrade ci to `ubuntu-latest` instead of `ubuntu-20.04`

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#277]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/DoneXBlock/issues/247
- [ ] https://github.com/openedx/FeedbackXBlock/issues/113
- [ ] https://github.com/openedx/XBlock/issues/780
- [ ] https://github.com/openedx/edx-notes-api/issues/424
- [ ] https://github.com/openedx/opaque-keys/issues/332
- [ ] https://github.com/openedx/openedx-learning/issues/210
- [ ] https://github.com/openedx/xblock-in-video-quiz/issues/205
- [ ] https://github.com/openedx/event-bus-redis/pull/123
- [ ] https://github.com/openedx/xapi-db-load/pull/126
- [ ] https://github.com/openedx/xblock-sdk/pull/400
```

**Comment by irtazaakram** [comment]
Hi @feanil,

These PRs are ready for review:

https://github.com/openedx/DoneXBlock/pull/254
https://github.com/openedx/FeedbackXBlock/pull/117
https://github.com/openedx/XBlock/pull/787
https://github.com/openedx/edx-notes-api/pull/430
https://github.com/openedx/event-bus-redis/pull/123
https://github.com/openedx/opaque-keys/pull/338
https://github.com/openedx/openedx-learning/pull/224
https://github.com/openedx/xapi-db-load/pull/126
https://github.com/openedx/xblock-in-video-quiz/pull/210
https://github.com/openedx/xblock-sdk/pull/400

Thanks,

**Comment by feanil** [comment]
Nice! I've merged all those PRs, I think this task can be closed.
