### ISSUE TITLE
Remove `npm publish` for MFEs

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/public-engineering#284]
Looks like in the old days, we pushed MFEs to the npm registry but we stopped doing this (Last publish on npm dated back to 3 years ago) for some reason, but still, some of the MFEs have related actions, and packages.

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/366
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/415
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/490
```
