### ISSUE TITLE
Update `frontend-app-ora-grading` to use Design Tokens

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/public-engineering#304]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/394
- [ ] Ensure draft PR is using released versions of `paragon`/`frontend-build`/`frontend-platform` from `npm`
- [ ] Set up sandbox to test draft PR
- [ ] Get draft PR approved
- [ ] Create new `master-design-tokens` branch off of latest `master`
- [ ] Update PR to point to `master-design-tokens`, move out of draft
- [ ] Merge PR
```

**Comment by dcoa** [comment]
Work in progress https://github.com/openedx/frontend-app-ora-grading/pull/394/files
