### ISSUE TITLE
[DEPR]: Legacy Problem Editor

### ISSUE THREAD

**Issue by kdmccormick** [openedx/public-engineering#314]
### Proposal Date

2025-02-18

### Target Ticket Acceptance Date

2025-03-04

#### Teak - Deprecated but available

* New editor will be the default. Legacy problem editor will require explicit opt-out.
* Opting out will also require opting out of the new Unit editor.
* As mentioned in the [Legacy Unit Editor DEPR](https://github.com/openedx/edx-platform/issues/35261), opting out of the new Unit editor will mean missing out on new Content Libraries features.

#### Ulmo - Removed

* Legacy problem editor will be completely removed.

### Rationale

The legacy ProblemBlock (aka "CAPA") editor is based on outdated frontend technologies that do not integrate well with the new React-based Studio micro-frontend. There is a newer React-based editor that replaces it. Supporting both editors is a major burden for maintenance and feature development.

### Removal

The old pop-up modal Problem editor will be removed.

[ NEED: SCREENSHOT ] 

[ NEED: CODE LINKS ]

### Replacement

The full-screen React-based Problem editor is the replacement.

[ NEED: SCREENSHOT ]

CODE: https://github.com/openedx/frontend-lib-content-components/

### Deprecation

We will warn about the pending deprecation in the Sumac release notes.

### Migration

TBD

### Additional Info

Pending:
* Implementation of https://openedx.atlassian.net/wiki/spaces/COMM/pages/4517232656/Re-enable+Markdown+editing+of+CAPA+problems+to+meet+various+use+cases
* https://github.com/openedx/frontend-app-authoring/issues/1644

There is a known feature delta between the old editor and the new one. This includes:

- [ ] The default **Markdown** editing mode is removed and replaced with a default **WSISWYG** editing mode.
- [ ] **Multi-response problems,** which supported in Markdown, are not supported in WSIWYG (they are still available in the advanced editing mode.
- [ ] The **Advanced** (raw XML) editing mode is now nested under "Advanced Settings"
- [ ] The editor takes up the full screen and cannot be minimized.
- [ ] The editor cannot be opened in a new tab with right click.

[ NEED: SCREENSHOTS ]

Additional feedback on the new editor:
- @Sidnani: 
  > "Overall, it took someone between 2-10 times as long to build content in the new MFE editors vs. the Legacy editors.  Building a basic assessment item, like a Multiple Choice Question, from content written elsewhere went from 30 seconds in Legacy to 3 minutes with the forms required in the MFE editor. Advanced Editors are also a couple of more clicks to access. Toggling back and forth between the Advanced and Basic editors required to preview and complete LaTeX content became more time consuming. (This is where we get into content taking 10 times or more to build.)" 
- [ NEED: Finish compiling feedback ]

### Task List

TBD
