### ISSUE TITLE
[DEPR]: Replace cs_comments_service and remove MongoDB usage for forums

### ISSUE THREAD

**Issue by regisb** [openedx/public-engineering#424]
### RFC Start Date

2024-04-16

### Target Plan Accepted Date

2024-10-16

### Target Transition Unblocked Date

2025-04-06

### Earliest Breaking Changes Unblocked Date

2025-05-06

### Earliest Open edX Named Release Without This Functionality

Ulmo - 2025-05

### Rationale

The Open edX forum is an essential feature of the platform. In technical terms, it is a web application that is developed in the [cs_comments_service](https://github.com/openedx/cs_comments_service) repository. This application is implemented in the Ruby programming language. Only a few Open edX contributors have expertise in Ruby: most developers are skilled in Python and NodeJS. This makes it extremely difficult to implement new features and extend the forum.

Moreover, the cs_comments_service application currently stores data in MongoDB, which is neither a consistent or a relational data storage solution -- as opposed to MySQL. This results both in operational and architecture complexity, as some data needs to be synced up between the two data stores (notably for user data).

### Removal

The [cs_comments_service](https://github.com/openedx/cs_comments_service) repository will be removed. Note howerver that the [tutor-forum](https://github.com/overhangio/tutor-forum/) plugin will be maintained, though it will be considerably simplified.

### Replacement

The Ruby application will be replaced by a Django app, currently being developed in the following repository: https://github.com/edly-io/forum/ (soon to be migrated to the openedx organization, as per [this public-engineering issue](https://github.com/openedx/axim-engineering/issues/1272)).

### Deprecation

The cs_comments_service repository will include a deprecation notice in its README file. Migration will be transparent for most users running Tutor, as the tutor-forum plugin will smoothly transition from running the former ruby app to installing the new forum application in the edx-platform runtime.

#### Strategy

Let's call the legacy cs_comments_service "forum v1" and the new forum application "forum v2".

In forum v1, edx-platform communicates with the Ruby application via an HTTP rest API. All calls are made from the backend, Client-side API calls are made to edx-platform, which then forwards parts of the requests to forum v1.

In forum v2, these API calls take the form of a native Python API. This is made possible by the fact that the forum v2 application is installed in the same runtime as edx-platform.

![image](https://github.com/user-attachments/assets/fab6c639-7b34-4454-aa9c-1c77aa54e23a)

This means that the diagram above will remain the same in the transition from v1 to v2. The only difference is that in step 3, communication will change from an HTTP API call to a native Python function call.

For storage, forum v2 will implement two different backends: one for MySQL (in the form of Django models) and one for MongoDB. The MongoDB backend is only preserved to ease the transition from v1 to v2; it is expected that it will be eventually removed.

#### Opt-out

Forum v2 will make use of two CourseWaffleFlag ([source code](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/waffle_utils/__init__.py)). For every course, platform administrators will have the choice to:

1. Send HTTP requests to the forum v1 app or native API calls to the forum v2 app.
2. If calling the forum v2 app, use either the legacy MongoDB backend or the new MySQL backend.
3. Run a dedicated migration command that will copy the course data from MongoDB to the new MySQL models.

By default, users running Tutor (and the tutor-forum plugin) will automatically transition from v1 to v2 and the MySQL models. In that sense, the transition is opt-out rather than opt-in.

#### Proposed timeline

- July - October 23rd 2024: implementation of forum v2
- October 23rd 2024:  Forum v1 marked for deprecation: no new change accepted in the cs_comments_service repository.
- October 23rd - December 9th 2024: Sumac testing, fixing issues in forum v2.
- December 9th 2024: Sumac release
    - By default, Tutor will run forum v2. The storage backend will depend on whether or not it's a new tutor installation
      - Existing platforms will keep using MongoDB: instructions to migrate will be printed on tutor ... launch and be available in the tutor-forum [README](https://github.com/overhangio/tutor-forum/).
      - New platforms will default to the MySQL backend.
    - It will be possible to override this default behavior on a course-per-course basis.
- December 2024 - April 2025: all platforms are expected to migrate from forum v1 to forum v2, with the MySQL storage backend.
- June 2025: Teak release:
    - the forum v1 integration is removed from edx-platform
    - the mongodb backend is removed from forum v2

### Additional Info

- This project was first announced in April 2024 here: https://discuss.openedx.org/t/axim-funded-contribution-proposal-forum-rewrite-from-ruby-mongodb-to-python-mysql/12788
- DEPR Announcement: https://discuss.openedx.org/t/deprecation-removal-forum-cs-comments-service-437/14056
- Then the technical implementation was discussed here: https://docs.google.com/document/d/1oa-L-ETJkXIPEOxLLOlcENE49o3kSh_HNVp-5gouwAc/edit
- Implementation of the forum v2 app started in July 2024 and project was managed publicly here: https://github.com/orgs/edly-io/projects/1/views/1
- DEPR announcement: https://discuss.openedx.org/t/deprecation-removal-forum-cs-comments-service-437/14056
- For reference, here are the guidelines for deprecation announcements: https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html

### Task List

- [x] Migrate the edly-io/forum repository to the openedx organisation: https://github.com/openedx/axim-engineering/issues/1272
- [x] Merge the following pull request in edx-platform: https://github.com/openedx/edx-platform/pull/35671
- [x] Update the tutor-forum plugin to replace forum v1 by forum v2
- [x] Document the opt-out strategy in forum v2
- [x] Testing: 
    - [x] Forum v2 and MySQL storage: tested during the Sumac testing period
    - [ ] Migration from MongoDB to MySQL: coordinate with 2U to test the correctness of the migration scripts.

### Removal PRs

These PRs directly remove the cs_comments_service calling code:

- [x] https://github.com/openedx/edx-platform/pull/36664
- [ ] https://github.com/openedx/edx-platform/pull/36706

**Comment by ayub02** [comment]
@ormsbee thank you for thinking through this. I want to clarify a few things: 

1. There’s been a misunderstanding about discussion xblocks. 2U does not and never intended to deprecate discussion xblocks. This old repo is causing this confusion and has nothing to do with discussion xblocks that are being used in 2U and by community: https://github.com/openedx-unsupported/xblock-discussion. Here’s is the link to the discussion xblock code currently in use: https://github.com/openedx/edx-platform/blob/f9126bfdd990dc78c97d10619bd2b08ad47a1a18/xmodule/discussion_block.py#L39
3. Our understanding is that forum v2 is a replacement for cs_comment_service. Which means that it needs to support everything that cs_comment_service supports at present, including discussion xblocks.
4. The image below illustrates the impact of flags on overall discussions experience. Note that the non-MFE UI and discussion xblocks are default experiences for community at present.
5. Rollout doc for discussions MFE experience: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3509551260/New+discussions+forum+experience (explanation of some features may be outdated)
6. Rollout doc for "openedx" discussion provider (a.k.a discussion sidebar): https://openedx.atlassian.net/wiki/spaces/COMM/pages/3470655498/Discussions+upgrade+Sidebar+and+new+topic+structure (explanation of some features may be outdated)

The only way forward that makes sense to me is fixing forum v2 to work with discussion xblocks. 

Also, i'll avoid using the word "legacy" in conversations because it may give a false indication of a pending deprecation. Except that the old discussion provider was renamed to "legacy" by OpenCraft during BD-38 ("old" for 2U, not for community).

I hope this helps.

![Image](https://github.com/user-attachments/assets/3fa7bf74-c626-4e63-9c4c-095b349eb74e)

**Comment by kdmccormick** [comment]
@ormsbee Checking my understanding, is it true that neither this DEPR nor https://github.com/openedx/edx-platform/issues/36229 include removing the DiscussionXBlock?

Do you know what the deprecation and removal timeline would be for those, or have we resolved to support the block in some form forever?

Since aximprovements is currently working on the [xblock extraction intiative](https://github.com/openedx/edx-platform/issues/34827), I need to decide whether to have them extract the DiscussionXBlock, or leave it in place with the understanding that it will be removed soon. I'm loosely aiming to have all legacy LMS frontends removed by late 2026, which would need to include either the extraction or the removal of the DiscussionXBlock.

**Comment by ormsbee** [comment]
> [@ormsbee](https://github.com/ormsbee) Checking my understanding, is it true that neither this DEPR nor [openedx/edx-platform#36229](https://github.com/openedx/edx-platform/issues/36229) include removing the DiscussionXBlock?

Correct.

> Do you know what the deprecation and removal timeline would be for those, or have we resolved to support the block in some form forever?

I haven't proposed a DEPR for it yet because I'm still trying to figure out if we can make a decent migration path for existing content.

> Since aximprovements is currently working on the [xblock extraction intiative](https://github.com/openedx/edx-platform/issues/34827), I need to decide whether to have them extract the DiscussionXBlock, or leave it in place with the understanding that it will be removed soon. I'm loosely aiming to have all legacy LMS frontends removed by late 2026, which would need to include either the extraction or the removal of the DiscussionXBlock.

I think it makes sense to schedule it for extraction.

**Comment by robrap** [comment]
@ormsbee: [inform] I moved this from "Replacement Ready" back to "Accepted", but maybe the replacement is fully ready at this point? The proposed timeline and target dates seem out of date. It would be great to update this ticket at some point, and then put it back in "Replacement Ready" once it is actually ready (which is when)?

**Comment by ormsbee** [comment]
@robrap: Replacement is ready. Breaking changes were delayed until Teak was cut, to give more time to work on migration-related issues. Now that Teak has been cut, we're proceeding with breaking changes that force edx-platform to use the new v2 forums API internally and don't allow fallback to the Ruby service. The first such PR is:

https://github.com/openedx/edx-platform/pull/36664/files

For anybody watching, there are weekly check-in meetings. The [notes ](https://docs.google.com/document/d/1qzw8BfsELTIs914KJrqeMlRBisH_hdKaMJO1_Sv_EtU/edit?tab=t.0) are public. Current attendees are from 2U, MIT, Edly, and Axim. If you would like to attend, please message me on Slack. Thank you.

**Comment by robrap** [comment]
Great. Thank you for the update to the ticket and good luck with the rest of the work.

**Comment by feanil** [comment]
Update: More removal are continuing to happen and we're dropping it piecemeal to ensure we don't break anything.

https://github.com/openedx/edx-platform/pulls?q=is%3Apr+cs_comments_service

**Comment by kaustavb12** [comment]
What is the current target timeline for the removal of the mongodb backend from Forum v2?

The timeline section above mentions Teak as the target release, but as I understand from the discussions above, this was delayed due to blockers. Is Ulmo the current target release for the removal of the mongodb backend ?

**Comment by ormsbee** [comment]
All `cs_comments_service` usage will be removed by Ulmo, but MongoDB support in v2 forums won't be removed until Verawood. That work will be done under a separate funded contribution that won't be scheduled until after the current ruby service deprecation and bug fixing work is complete.

**Comment by kaustavb12** [comment]
@ormsbee Thank you for the context about the timelines.

The reason why I enquired about removal of mongodb backend, was that recently on migration of some long running courses (with large volumes of discussion data) to MySQL, we noticed significant performance issues which forced us to revert to using MongoDB for those large courses. We were trying to determine the next steps for us based on how soon mongodb is planned to be removed.

I have reported this [issue here](https://github.com/openedx/forum/issues/235).

**Comment by ormsbee** [comment]
@kaustavb12: Thank you for your report. The team is looking at it now.

**Comment by ormsbee** [comment]
Update: As of https://github.com/openedx/edx-platform/pull/37376, edx-platform no longer calls out the cs_comments_service for anything. I'll archive the cs_comments_service repo next week.

To reiterate: MongoDB is still supported at this time and in the Ulmo release.

**Comment by ormsbee** [comment]
I'm archiving the cs_comments_service, and moving this DEPR issue to public-engineering as part of that process (see [OEP-14](https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0014-proc-archive-repos.html#archive-steps)).

**Comment by feanil** [comment]
@ormsbee is there a separate Mongo->mysql depr ticket so that this one can be closed?  Or is this ticket still open until we drop mongo support?

**Comment by ormsbee** [comment]
@feanil: If I had it to do over again, I'd have them separated. But since we've been tracking and discussing it all here, let's just keep this ticket.

**Comment by kdmccormick** [comment]
is Breaking Changes Unblocked the right status for MongoDB-backed forums? in other words, can Mongo forums support be safely dropped now?

**Comment by ormsbee** [comment]
Yes.

**Comment by salman2013** [comment]
This deprecation has been done under following issue. 
https://github.com/openedx/public-engineering/issues/502
PR: https://github.com/openedx/forum/pull/274

**Comment by ormsbee** [comment]
@salman2013: Can you please update the [Verawood operator release notes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/5331222534/Verawood+-+Operator+Release+Notes) to include this information? Thank you!
